# Generated by Django 2.2.1 on 2020-01-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='quotastart',
        ),
    ]
