# Generated by Django 2.2.1 on 2020-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200115_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
