# Generated by Django 2.2.1 on 2019-12-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Event'),
            preserve_default=False,
        ),
    ]
