# Generated by Django 2.2.1 on 2020-01-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_event_quotastart'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quotastart',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
