# Generated by Django 2.2.1 on 2019-12-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_ticket_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
