# Generated by Django 2.2.1 on 2020-01-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200115_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
    ]
