# Generated by Django 2.2.1 on 2019-12-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191203_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isOperator',
            field=models.BooleanField(default=False),
        ),
    ]
